import type { Metadata } from "next";
import "../styles/globals.css";
import React from "react";
import Header from "../components/common/navbar";
import Footer from "../components/common/footer";

export const metadata: Metadata = {
  title: "DIANS Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}